### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by HippityHarry** [catouberos/video-store#65]
- [x] Add logo and store name in sign-in/sign-up page #66 
- [x] Add welcome scene for user #76 #82 
- [x] ~~Add images for video/game/movie~~ @catouberos: I'd suggest dropping this
- [ ] Add header/footer
- [x] Add 'help' button that open store description #81 
- [x] Fix the transparency of the name in logo #66
- [x] Add hint under sign-up options
- [x] Fix pop-up error messages #70 
- [x] Add confirmation messages for rent/change info actions #70 #72 
- [x] Display the User in the top right corner #68 
- [x] Add membership info (this could be integrated into the 'help' page tho) #77 
- [x] Add pop-up message when a user doesn't have enough membership to rent an item @catouberos: **this was already implemented**
- [x] ~~Display item by sorting by genre~~ @catouberos: I'd suggest dropping this due to the time complexity

**Comment by catouberos** [comment]
During the process, I've added an "I'm feeling lucky" feature on User Dashboard - #76

**Comment by catouberos** [comment]
For the "help" page, could add a "Contact" hyperlink that points to `mailto:contact@example.com` for demo purposes.
